# Generated by Django 3.1.4 on 2021-02-02 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_and_author', '0044_auto_20210201_1803'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='authors',
            new_name='author_id',
        ),
    ]
