# Generated by Django 3.1.4 on 2021-02-03 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_and_author', '0049_auto_20210203_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_and_author.author'),
        ),
    ]
