# Generated by Django 3.1.4 on 2021-02-03 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_and_author', '0050_auto_20210203_1802'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='authors',
            new_name='author_id',
        ),
    ]
