# Generated by Django 3.1.4 on 2021-02-03 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_and_author', '0052_auto_20210203_1812'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='author_id',
            new_name='authors',
        ),
    ]
